---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour-certgen
  namespace: {{ .Release.Namespace }}
